# Generated by Django 2.2.5 on 2020-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
